# Generated by Django 4.1.4 on 2022-12-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogger', '0002_alter_post_content_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
